### ISSUE TITLE
Verify function

### ISSUE THREAD

**Issue by DominiqueMakowski** [RealityBending/InteroceptionScale#1]
https://github.com/RealityBending/InteroceptionScale/blob/480dee6f630bb673354f9b4f9055cdf87f2f597f/study1/experiment/intero.js#L262-L277

Please double check to make sure that this is correct, thanks

**Comment by AnafNeves** [comment]
The scoring is right, the ones that ask to score to the left are coded as 1-attentioncheck

Is that what you wanted me to check ?

**Comment by DominiqueMakowski** [comment]
yes, thx

**Comment by AnafNeves** [comment]
it also works on the console, it does compute the average 

>check_attentionchecks()
0.5476190476190477
